package com.phicomm.ws.pi021;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-03-23T15:26:41.070+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://phicomm.com/WMS/PI021/DeliveryList", name = "DeliveryList_OUT")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DeliveryListOUT {

    @WebResult(name = "DeliveryList_Res", targetNamespace = "http://phicomm.com/WMS/PI021/DeliveryList", partName = "DeliveryList_Res")
    @WebMethod(operationName = "DeliveryList_OUT", action = "http://sap.com/xi/WebService/soap1.1")
    public DeliveryListRes deliveryListOUT(
        @WebParam(partName = "DeliveryList_Req", name = "DeliveryList_Req", targetNamespace = "http://phicomm.com/WMS/PI021/DeliveryList")
        DeliveryListReq deliveryListReq
    );
}
