
package com.swk.interfce.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4
 * Sat Dec 26 21:40:07 CST 2015
 * Generated source version: 3.1.4
 */

@XmlRootElement(name = "sayHello", namespace = "http://interfce.swk.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sayHello", namespace = "http://interfce.swk.com/")

public class SayHello {


}

